## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows
  - bsd

julia:
  - 1.5
  - nightly

notifications:
  email: false

sudo: false

git:
  depth: 99999999

jobs:
  include:
    - stage: test
      script:
        - julia --color=yes --project=test -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project=test test/runtests.jl
      julia: 1.5

    - stage: test
      script:
        - julia --color=yes	--project=test -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes	--project=test test/runtests.jl
      julia: nightly